### ISSUE TITLE
Missing definition of gpt.gauge_fix

### ISSUE THREAD

**Issue by Greyyy-HJC** [philomat/gpt_utils#1]
Hi Philipp,

I tried to run the script but I found that the function for gauge fixing "gpt.gauge_fix" is not defined.

I also searched your "gpt" repo, but still could not find the definition of "gpt.gauge_fix". Do you know where to find it?

Regards,
Jinchen

**Comment by philomat** [comment]
Hi Jinchen,

the gauge fixing to Coulomb gauge that I implemented is not a gpt python function but uses a cgpt function, that implements the basic Grid gauge fixing. You can find it in my fork of gpt, but you have to use either the branch scior or the branch scior_proton. Then you find the function implemented in lib/cgpt/lib/gauge_fix.cc

If everything is compiled successfully gpt.gauge_fix should be defined. But I did that quite a while ago ;)
If it doesn't work, I would suggest to build a Coulomb gauge fixing function in gpt like Christoph already did for Landau gauge:
/lib/gpt/qcd/gauge/fix/landau.py

Best regards,

Philipp

**Comment by Greyyy-HJC** [comment]
Thank you for the clarification.
